/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const Head: typeof import('@inertiajs/vue3').Head
  const Link: typeof import('@inertiajs/vue3').Link
  const PLATE_MAX_TOTAL: typeof import('../lib/licensePlate').PLATE_MAX_TOTAL
  const PLATE_MESSAGES: typeof import('../lib/licensePlate').PLATE_MESSAGES
  const VEHICLE_BRANDS: typeof import('../lib/vehicleBrands').VEHICLE_BRANDS
  const VEHICLE_BRAND_OPTIONS: typeof import('../lib/vehicleBrands').VEHICLE_BRAND_OPTIONS
  const cn: typeof import('../lib/utils').cn
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getInitials: typeof import('../composables/useInitials').getInitials
  const getOffRampLabel: typeof import('../lib/orderFlow').getOffRampLabel
  const getOrderFlowSteps: typeof import('../lib/orderFlow').getOrderFlowSteps
  const getVehicleStatusDisplay: typeof import('../lib/vehicleStatus').getVehicleStatusDisplay
  const h: typeof import('vue').h
  const initializeTheme: typeof import('../composables/useAppearance').initializeTheme
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isTerminalOffRamp: typeof import('../lib/orderFlow').isTerminalOffRamp
  const isVehicleCompleted: typeof import('../lib/vehicleStatus').isVehicleCompleted
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizePlate: typeof import('../lib/licensePlate').normalizePlate
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const platePartsLength: typeof import('../lib/licensePlate').platePartsLength
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const router: typeof import('@inertiajs/vue3').router
  const sanitizePlateNumber: typeof import('../lib/licensePlate').sanitizePlateNumber
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toPlateUpperCase: typeof import('../lib/licensePlate').toPlateUpperCase
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateTheme: typeof import('../composables/useAppearance').updateTheme
  const useAppearance: typeof import('../composables/useAppearance').useAppearance
  const useAttrs: typeof import('vue').useAttrs
  const useClipboard: typeof import('@vueuse/core').useClipboard
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDark: typeof import('@vueuse/core').useDark
  const useDebounceFn: typeof import('@vueuse/core').useDebounceFn
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useId: typeof import('vue').useId
  const useInitials: typeof import('../composables/useInitials').useInitials
  const useLocalStorage: typeof import('@vueuse/core').useLocalStorage
  const useModel: typeof import('vue').useModel
  const usePage: typeof import('@inertiajs/vue3').usePage
  const useRemember: typeof import('@inertiajs/vue3').useRemember
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToggle: typeof import('@vueuse/core').useToggle
  const validatePlateCity: typeof import('../lib/licensePlate').validatePlateCity
  const validatePlateLetters: typeof import('../lib/licensePlate').validatePlateLetters
  const validatePlateNumber: typeof import('../lib/licensePlate').validatePlateNumber
  const validatePlateParts: typeof import('../lib/licensePlate').validatePlateParts
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { OrderFlowStep } from '../lib/orderFlow'
  import('../lib/orderFlow')
  // @ts-ignore
  export type { VehicleStatusDisplay } from '../lib/vehicleStatus'
  import('../lib/vehicleStatus')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Head: UnwrapRef<typeof import('@inertiajs/vue3')['Head']>
    readonly Link: UnwrapRef<typeof import('@inertiajs/vue3')['Link']>
    readonly PLATE_MAX_TOTAL: UnwrapRef<typeof import('../lib/licensePlate')['PLATE_MAX_TOTAL']>
    readonly PLATE_MESSAGES: UnwrapRef<typeof import('../lib/licensePlate')['PLATE_MESSAGES']>
    readonly VEHICLE_BRANDS: UnwrapRef<typeof import('../lib/vehicleBrands')['VEHICLE_BRANDS']>
    readonly VEHICLE_BRAND_OPTIONS: UnwrapRef<typeof import('../lib/vehicleBrands')['VEHICLE_BRAND_OPTIONS']>
    readonly cn: UnwrapRef<typeof import('../lib/utils')['cn']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getInitials: UnwrapRef<typeof import('../composables/useInitials')['getInitials']>
    readonly getOffRampLabel: UnwrapRef<typeof import('../lib/orderFlow')['getOffRampLabel']>
    readonly getOrderFlowSteps: UnwrapRef<typeof import('../lib/orderFlow')['getOrderFlowSteps']>
    readonly getVehicleStatusDisplay: UnwrapRef<typeof import('../lib/vehicleStatus')['getVehicleStatusDisplay']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly initializeTheme: UnwrapRef<typeof import('../composables/useAppearance')['initializeTheme']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isTerminalOffRamp: UnwrapRef<typeof import('../lib/orderFlow')['isTerminalOffRamp']>
    readonly isVehicleCompleted: UnwrapRef<typeof import('../lib/vehicleStatus')['isVehicleCompleted']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizePlate: UnwrapRef<typeof import('../lib/licensePlate')['normalizePlate']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly platePartsLength: UnwrapRef<typeof import('../lib/licensePlate')['platePartsLength']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly router: UnwrapRef<typeof import('@inertiajs/vue3')['router']>
    readonly sanitizePlateNumber: UnwrapRef<typeof import('../lib/licensePlate')['sanitizePlateNumber']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toPlateUpperCase: UnwrapRef<typeof import('../lib/licensePlate')['toPlateUpperCase']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateTheme: UnwrapRef<typeof import('../composables/useAppearance')['updateTheme']>
    readonly useAppearance: UnwrapRef<typeof import('../composables/useAppearance')['useAppearance']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>
    readonly useForm: UnwrapRef<typeof import('@inertiajs/vue3')['useForm']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInitials: UnwrapRef<typeof import('../composables/useInitials')['useInitials']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePage: UnwrapRef<typeof import('@inertiajs/vue3')['usePage']>
    readonly useRemember: UnwrapRef<typeof import('@inertiajs/vue3')['useRemember']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly validatePlateCity: UnwrapRef<typeof import('../lib/licensePlate')['validatePlateCity']>
    readonly validatePlateLetters: UnwrapRef<typeof import('../lib/licensePlate')['validatePlateLetters']>
    readonly validatePlateNumber: UnwrapRef<typeof import('../lib/licensePlate')['validatePlateNumber']>
    readonly validatePlateParts: UnwrapRef<typeof import('../lib/licensePlate')['validatePlateParts']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}