// Shared, single source of truth for the vehicle "Marke" (brand) dropdown.
// Order is intentional (alphabetical as provided) and special characters
// (Citroën, Škoda, …) must be preserved exactly.
import type { SelectFieldOption } from '@/components/form/SelectField.vue';

export const VEHICLE_BRANDS: readonly string[] = [
    'Abarth',
    'Aiways',
    'Alfa Romeo',
    'Alpine',
    'Audi',
    'Bentley',
    'BMW',
    'BYD',
    'Cadillac',
    'Citroën',
    'Cupra',
    'Dacia',
    'DS Automobiles',
    'Fiat',
    'Ford',
    'Genesis',
    'Honda',
    'Hyundai',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lancia',
    'Land Rover / Range Rover',
    'Lexus',
    'Lotus',
    'Lucid',
    'Lynk & Co',
    'Maserati',
    'Mazda',
    'Mercedes-Benz',
    'MG',
    'Mini',
    'Mitsubishi',
    'Nio',
    'Nissan',
    'Opel',
    'Peugeot',
    'Polestar',
    'Porsche',
    'Renault',
    'SEAT',
    'Škoda',
    'smart',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
    'XPeng',
] as const;

/** Ready-to-use options for SelectField. */
export const VEHICLE_BRAND_OPTIONS: SelectFieldOption[] = VEHICLE_BRANDS.map((brand) => ({ label: brand, value: brand }));
